-include .env

.PHONY: all

all: build

clean:
	forge clean

build-clean: clean build

build:
	forge build

test-dsc:
	forge test --match-path test/DecentralizedStableCoin.test.sol -vvvv

test-dsc-engine:
	forge test --match-path test/DSCEngine.test.sol -vvvv

format:
	forge fmt

install:
	forge install openzeppelin/openzeppelin-contracts --no-commit && forge install foundry-rs/forge-std --no-commit && forge install smartcontractkit/chainlink-brownie-contracts --no-commit